---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
  labels:
    istio-injection: disabled
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-public
  labels:
    istio-injection: disabled
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-node-lease
  labels:
    istio-injection: disabled
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    istio-injection: disabled
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
