---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    istio-injection: disabled
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vault-api
  namespace: vault
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: vault
      component: server
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: vault
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: crossplane-system
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: cert-manager
    {{- with .Values.apiIngressPeers }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    ports:
    - port: 8200
      protocol: TCP
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: vault
          component: server
    ports:
    - port: 8201
      protocol: TCP
